<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CrashDump" Version="1.7.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.Fakes" Version="17.14.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.HangDump" Version="1.7.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.HotReload" Version="1.7.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.Retry" Version="1.7.2" />
    <PackageVersion Include="System.Text.Json" Version="10.0.11" />
    <PackageVersion Include="Polyfill" Version="11.2.0" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <PackageVersion Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
  </ItemGroup>
</Project>
